<?php

namespace Prototype\PageBundle\Repository;

/**
 * LocalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalesRepository extends \Doctrine\ORM\EntityRepository
{
}
