<?php

namespace Prototype\PageBundle\Repository;

/**
 * PageTranslationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTranslationsRepository extends \Doctrine\ORM\EntityRepository
{
	//FIND ALL TRANSLATIONS FOR PAGE WITH ID
	public function getAvailableLanguagesForPageId($pageid)
	{
		$query = $this->getEntityManager()->createQuery(
			'SELECT UNIQUE p.locale, p.language FROM PrototypePageBundle:PageTranslations p WHERE p.foreign_key = :pageid '
			);
		$query->setParameter('pageid', $pageid);
		$results = $query->getArrayResult();

		print_r($results);

		return $results;
	}


	public function findAllByLocale($locale = 'en')
   {
	   //Make a Select query
	   $qb = $this->createQueryBuilder('a');
	   $qb->select('a');

	   // Use Translation Walker
	   $query = $qb->getQuery();
	   $query->setHint(
		   \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
		   'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
	   );
	   // Force the locale
	   $query->setHint(
		   \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
		   $locale
	   );
	   return $query->getArrayResult();
   }

}
